--- #EC2 AMI copy from one location to another 
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscred.yml
  tasks:
  - name: Copy AMI from one location to another
    ec2_ami_copy:
     aws_access_key: "{{ aws_id }}"
     aws_secret_key: "{{ aws_key }}"
     region: "{{ aws_region }}"
     source_region: "{{ aws_region }}"
     source_image_id: <ami-id>
     wait: no
     name: us-east-ami1
     tags:
      Name: Myeast-ami
      Service: east-ami-service
    register: instance
